Repository hangry-ateball/hangry-ateball-fe, pull requests merged in 2020-04, with the labels that each got.

#7 Initial layout
  App.js
  Components/Form/Form.js
  assets/ate-ball-home.png
  package-lock.json
Labels: enhancement, frontend, phase 1

#8 Initial layout
  App.js
  Components/Form/Form.js
  Components/ResultPage/ResultPage.js
Labels: enhancement, frontend, phase 1

#13 Maps integration
  package-lock.json
  package.json
  src/screens/FormScreen.js
  src/screens/ResultScreen.js
Labels: enhancement, frontend, phase 2

#15 Test setup
  package-lock.json
  package.json
  src/screens/StartScreen.test.js
  src/screens/__snapshots__/StartScreen.test.js.snap
Labels: chore, frontend

#24 fav-past-ui
  src/screens/tabs/FavsTab.js
  src/screens/tabs/PrevTab.js
Labels: enhancement, frontend, phase 3

#26 Refactor data
  src/screens/FormScreen.js
  src/screens/ResultScreen.js
  yarn.lock
Labels: chore, enhancement, frontend, phase 3

#27 Setup cypress
  .travis.yml
  App.js
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/App_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/screens/FormScreen.js
Labels: frontend

#34 Previous functionality
  package-lock.json
  package.json
  src/screens/ResultScreen.js
  src/screens/asyncStorageHelper.js
  src/screens/tabs/PrevTab.js
Labels: Phase 4, enhancement, frontend

#36 Manual address
  app.json
  src/screens/ResultScreen.js
Labels: frontend

#38 Texting func
  package-lock.json
  package.json
  src/apiCalls.js
  src/components/ContactCard.js
  src/components/ContactsModal.js
  src/contactsHelper.js
  src/screens/FormScreen.js
  src/screens/ResultScreen.js
  src/screens/tabs/MaterialBottomTabs.js
Labels: enhancement, frontend

#40 Favorite functionality
  assets/favorite.png
  assets/magic-loader-img.png
  assets/unfavorite.png
  src/screens/ResultScreen.js
  src/screens/asyncStorageHelper.js
  src/screens/tabs/FavsTab.js
  src/screens/tabs/PrevTab.js
Labels: Phase 4, enhancement, frontend
